-- Fix user_profiles to work standalone without Supabase Auth
-- Remove foreign key constraint to auth.users since we're managing users ourselves

-- Step 1: Drop the foreign key constraint
ALTER TABLE user_profiles 
DROP CONSTRAINT IF EXISTS user_profiles_id_fkey;

-- Step 2: The id column will now be a standalone UUID PRIMARY KEY
-- No changes needed to the column definition, just removing the FK constraint

-- Note: This allows us to create user profiles independently
-- The id will be generated by the application (UUID.randomUUID())

